# Generated by Django 4.0.6 on 2022-07-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SC08A', '0002_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='motor_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='motor',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
