# Generated by Django 4.0.6 on 2022-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SC08A', '0003_motor_motor_name_alter_motor_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='channel_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
