# Generated by Django 4.0.6 on 2022-08-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SC08A', '0004_alter_motor_channel_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
